#!/usr/bin/env bun
/**
 * generate-version-header.ts — MC2.12 code-generator for the C++ side of
 * the runtime version constant.
 *
 * The mobile client binary reports `OnlookRuntime.version` to JS so the
 * relay can refuse bundles built against an incompatible runtime. The
 * single source of truth for that version is
 * `@onlook/mobile-client-protocol`'s `ONLOOK_RUNTIME_VERSION` export
 * (see `packages/mobile-client-protocol/src/runtime-version.ts`).
 *
 * Rather than duplicate the string in C++, this script reads the TS
 * constant and writes `apps/mobile-client/cpp/OnlookRuntime_version.generated.h`
 * with a `#define ONLOOK_RUNTIME_VERSION_STRING "..."` that
 * `OnlookRuntime_version.cpp` then consumes. Running before xcodebuild
 * guarantees the binary can never drift from the TS constant.
 *
 * The generated header is .gitignored — run this script as a build
 * pre-step (wired into `run-build.ts`) or directly:
 *
 *   bun run scripts/generate-version-header.ts
 *   bun run scripts/generate-version-header.ts --dry-run
 *
 * Exit code: 0 on success, 1 on any failure (missing constant, write
 * error, etc.).
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { ONLOOK_RUNTIME_VERSION } from '@onlook/mobile-client-protocol';

interface Options {
    dryRun: boolean;
    outputPath: string;
}

function defaultOptions(): Options {
    return {
        dryRun: false,
        outputPath: resolve(
            import.meta.dir,
            '..',
            'cpp',
            'OnlookRuntime_version.generated.h',
        ),
    };
}

export function parseArgs(argv: readonly string[], base: Options): Options {
    const opts: Options = { ...base };
    for (const arg of argv) {
        if (arg === '--dry-run') {
            opts.dryRun = true;
        } else if (arg.startsWith('--output=')) {
            opts.outputPath = resolve(arg.slice('--output='.length));
        }
    }
    return opts;
}

/**
 * Escape a string for safe embedding inside a C string literal. We only
 * need to handle the characters that can appear in a semver: digits, dots
 * and optional prerelease identifiers (`-`, alphanumerics). Anything else
 * is rejected outright so a stray quote or backslash never makes it into
 * generated C++ source.
 */
export function escapeForCStringLiteral(value: string): string {
    if (!/^[0-9A-Za-z.\-+]+$/.test(value)) {
        throw new Error(
            `ONLOOK_RUNTIME_VERSION "${value}" contains disallowed characters; ` +
                `refusing to generate C header`,
        );
    }
    return value;
}

export function renderHeader(version: string): string {
    const escaped = escapeForCStringLiteral(version);
    return (
        '// AUTO-GENERATED by apps/mobile-client/scripts/generate-version-header.ts.\n' +
        '// DO NOT EDIT. Source of truth: @onlook/mobile-client-protocol\n' +
        '//   (packages/mobile-client-protocol/src/runtime-version.ts).\n' +
        '// Regenerate with `bun run scripts/generate-version-header.ts`.\n' +
        '//\n' +
        '// MC2.12 of plans/onlook-mobile-client-task-queue.md.\n' +
        '\n' +
        '#pragma once\n' +
        '\n' +
        `#define ONLOOK_RUNTIME_VERSION_STRING "${escaped}"\n`
    );
}

function main(): number {
    const opts = parseArgs(process.argv.slice(2), defaultOptions());
    const mode = opts.dryRun ? '[dry-run] ' : '';

    if (!ONLOOK_RUNTIME_VERSION || typeof ONLOOK_RUNTIME_VERSION !== 'string') {
        console.error(
            `${mode}[generate-version-header] FAIL: ` +
                `ONLOOK_RUNTIME_VERSION is missing or not a string`,
        );
        return 1;
    }

    let contents: string;
    try {
        contents = renderHeader(ONLOOK_RUNTIME_VERSION);
    } catch (err) {
        console.error(
            `${mode}[generate-version-header] FAIL: ${(err as Error).message}`,
        );
        return 1;
    }

    console.log(
        `${mode}[generate-version-header] ONLOOK_RUNTIME_VERSION=${ONLOOK_RUNTIME_VERSION}\n` +
            `${mode}[generate-version-header] output: ${opts.outputPath}`,
    );

    if (opts.dryRun) {
        process.stdout.write(contents);
        return 0;
    }

    try {
        const parent = dirname(opts.outputPath);
        if (!existsSync(parent)) {
            mkdirSync(parent, { recursive: true });
        }
        writeFileSync(opts.outputPath, contents, 'utf8');
    } catch (err) {
        console.error(
            `${mode}[generate-version-header] FAIL: write error: ${(err as Error).message}`,
        );
        return 1;
    }

    console.log(`${mode}[generate-version-header] wrote ${contents.length} bytes`);
    return 0;
}

if (import.meta.main) {
    process.exit(main());
}
