/**
 * Tests for the mobile-client binary version SSOT.
 *
 * Task: MC6.1
 * Validate: bun test apps/mobile-client/src/__tests__/version.test.ts
 *
 * Asserts that the version exposed by `apps/mobile-client/src/version.ts`
 * matches `ONLOOK_RUNTIME_VERSION` from `@onlook/mobile-client-protocol`
 * (`packages/mobile-client-protocol/src/runtime-version.ts`) — the whole
 * point of MC6.1 is that these two values can never drift.
 *
 * We additionally check that the Expo app config (`app.config.ts`)
 * consumes the same constant, so the iOS `CFBundleShortVersionString`
 * and Android `versionName` generated by `expo prebuild` inherit the
 * SSOT without re-declaration.
 */

import { describe, expect, test } from 'bun:test';

import { ONLOOK_RUNTIME_VERSION } from '@onlook/mobile-client-protocol';

import appConfig from '../../app.config';
import { APP_VERSION, ONLOOK_RUNTIME_VERSION as RuntimeVersionReExport } from '../version';

describe('mobile-client version SSOT (MC6.1)', () => {
    test('APP_VERSION mirrors ONLOOK_RUNTIME_VERSION from the protocol package', () => {
        expect(APP_VERSION).toBe(ONLOOK_RUNTIME_VERSION);
    });

    test('APP_VERSION is a non-empty semver string', () => {
        expect(typeof APP_VERSION).toBe('string');
        expect(APP_VERSION.length).toBeGreaterThan(0);
        expect(APP_VERSION).toMatch(/^\d+\.\d+\.\d+$/);
    });

    test('re-exported ONLOOK_RUNTIME_VERSION is identical to the protocol export', () => {
        expect(RuntimeVersionReExport).toBe(ONLOOK_RUNTIME_VERSION);
    });

    test('app.config.ts version field consumes the SSOT', () => {
        // ExpoConfig.version feeds iOS CFBundleShortVersionString and
        // Android versionName via `expo prebuild`. Anchoring it to the
        // protocol constant is the whole MC6.1 hookup.
        expect(appConfig.version).toBe(ONLOOK_RUNTIME_VERSION);
    });

    test('app.config.ts runtimeVersion also consumes the SSOT', () => {
        // Keeps the relay manifest's extra.expoClient.onlookRuntimeVersion
        // (MC6.2) aligned with the binary.
        expect(appConfig.runtimeVersion).toBe(ONLOOK_RUNTIME_VERSION);
    });
});
